### ISSUE TITLE
Source code and data

### ISSUE THREAD

**Issue by dtchang** [sassan72/Quantum-Machine-learning#1]
The paper "Clinical data classification with noisy intermediate scale quantum computers" is an important and comprehensive work. This (5 skeleton codes) trivializes the work, and it is not what is promised in the paper: "The source code of the implemented quantum algorithms can be accessed by the link: https:// github. com/ sassan72/ Quantum-Machine-learning."

Please provide the full set of source code and data that are used to generate the results of the paper and the supplemental information.

**Comment by sassan72** [comment]
Thanks for your interest. Regarding data used in this paper you can ask the corresponding author. For your first question: there are three different quantum circuit that you can calculate the inner product of quantum states, which i have explained in the supplemental with details. 1- Hadamard Test 2- Swap Test and 3- and Hadamard Test and swap test without control qubit. If you run these three different quantum circuit on a noiseless quantum simulator, you will get the same results. But i you choose to use real noisy quantum devices the destructive swap test is better, since it does not need to use the control qubits, three qubit Toffoli gate, and Fredkin gate (controlled swap).  Toffoli gate and Fredkin gate are very expensive and noisy on real quantum devices. It will affect the prediction results. But if you use the Hadamard test and swap test without control qubit, you have only single rotation and CNOT gates which are very efficient. I used the third method for real quantum device to reduce the effect of noise to calculate the kernel matrix and inner product.

**Comment by dtchang** [comment]
Please provide the full set of source code and data that are used to generate the results of the paper and the supplemental information, as promised in the paper: "The source code of the implemented quantum algorithms can be accessed by the link: https:// github. com/ sassan72/ Quantum-Machine-learning."
